### PR TITLE
Updated Angular and Webpack packages

### PR DESCRIPTION
**Pull request by willwolfram18**
Angular was using RC packages, but Angular is now on to 2.4.8. Also went ahead and updated webpack while I was at it

### CODE REVIEW

**Comment by unseen1980** [comment]
Thanks for that, let me give it a try locally first. :facepunch:

**Comment by willwolfram18** [comment]
Definitely just realized I included changes beyond the NPM package updates since I didn't put the other changes in a separate branch. Totally my bad /facepalm

**Comment by willwolfram18** [comment]
As a reference, I was able to clone, `npm install` and start the project on Windows 7, 10, and OS X 10.11. I was also able to deploy to [Heroku](https://nodejs-angular-webpack-example.herokuapp.com)

**Comment by willwolfram18** [comment]
I realized, after doing some work on a project of my own, the changes I had made (aside from updating package versions) wasn't accomplishing what I had wanted. I wanted to set it up so that there was a `vendor.css/js` that was, for the most part, compiled once, and then the `main.js` where app code was being written to. However, the changes I made don't accomplish this at all, so I will go back to the drawing board and see if I can accomplish that!

**Comment by unseen1980** [comment]
That's ok mate. Both of us learned something. See you.

**Pull request closed without merging**
